token: "0123456789abcdef"    # Authentication token for target servers
port: 
  web: 8443
  grpc: 8444
tls: true
cert: /path/to/cert.pem   # not needed it tls = false
key: /path/to/key.pem     # not needed it tls = false
