name: my-listener-name
dispatcher:
  host: my-servlce.net:8080
  tls: false
  token: "0123456789abcdef"   # Has to match the server's auth token
actions:
- name: restart-service-1
  token: "1234567890123456789012345678901234567890"
  command: /home/user/scripts/restart.sh
- name: restart-service-2
  token: "0123456789012345678901234567890123456789"
  command: /home/user/scripts/restart.sh
